// React
import React, { useState } from "react";

// Componentes de NextJS
import Head from "next/head";
import { useRouter } from "next/router";


// Componentes
import { FlexRowLg10 } from "../components/Layout";
import { GeneralLayout } from "../components/Layout";

export default function homePage() {

  const router = useRouter();

  return (
    <GeneralLayout>
      <header>
        <div className="row">
          <div className="col-sm-2 col-lg-4"></div>
          <div className="col-sm-8 col-lg-4 d-flex flex-column justify-content-center align-items-center">
            <h1>Movimientos</h1>
            <p>
              <strong>
                <small>
                  Aquí puedes ver tus movimientos, tantos los activos como los
                  pasados
                </small>
              </strong>
            </p>
            <button
              className="btn btn-dark"
              onClick={() => {
                router.push("/new-movement");
              }}
            >
              Nuevo movimiento
            </button>
          </div>
          <div className="col-sm-2 col-lg-4"></div>
        </div>
      </header>
      <main>
        <FlexRowLg10 rowClasses="min80">
          <h2>Activos</h2>
        </FlexRowLg10>
        <FlexRowLg10>
          <h2>Pasados</h2>
        </FlexRowLg10>
      </main>
    </GeneralLayout>
  );

  return (
    <div className="cointainer min100">
      <Head>
        <title>My Camion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className="row">
          <div className="col-sm-2 col-lg-4"></div>
          <div className="col-sm-8 col-lg-4 d-flex flex-column justify-content-center align-items-center">
            <h1>Movimientos</h1>
            <p>
              <strong>
                <small>
                  Aquí puedes ver tus movimientos, tantos los activos como los
                  pasados
                </small>
              </strong>
            </p>
            <button
              className="btn btn-dark"
              onClick={() => {
                router.push("/new-movement");
              }}
            >
              Nuevo movimiento
            </button>
          </div>
          <div className="col-sm-2 col-lg-4"></div>
        </div>
      </header>
      <main>
        <FlexRowLg10 rowClasses="min80">
          <h2>Activos</h2>
        </FlexRowLg10>
        <FlexRowLg10>
          <h2>Pasados</h2>
        </FlexRowLg10>
      </main>

      <footer>
        <div className="row min20">
          <div className="col-12 d-flex flex-column justify-content-center align-items-center">
            <a
              href="https://www.leandrohornos.com"
              target="_blank"
              rel="noopener noreferrer"
            >
              <small>created by Leandro Hornos</small>
            </a>
          </div>
        </div>
      </footer>
    </div>
  );
}
