import Head from 'next/head'


export default function Login() {
  return (
    <div className="cointainer min100">
      <Head>
        <title>My Camion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="row min80">
          <div className="col-sm-2 col-lg-4"></div>
          <div className="col-sm-8 col-lg-4 d-flex flex-column justify-content-center align-items-center">
          <header>
            <h1>
                Ingresar
            </h1>
          </header>
          <form className="width100">
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Email</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" />
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" />
            </div>
            <button type="submit" class="btn btn-primary">Enviar</button>
            </form>
            <button className="btn btn-link">Olvidé mi password</button>
          </div>
          <div className="col-sm-2 col-lg-4"></div>
        </div>
        
      </main>
      <footer>
        <div className="row min20">
          <div className="col-12 d-flex flex-column justify-content-center align-items-center">
            <a
            href="https://www.leandrohornos.com"
            target="_blank"
            rel="noopener noreferrer"
          >
            created by Leandro Hornos
          </a>
          </div>
        </div>
      </footer>
    </div>
  )
}
